apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-ccdt-config
data:
  mq-ccdt.json: |-
    {
        "channel":
        [
            {
                "name": "DEV.APP.SVRCONN",
                "clientConnection":
                {
                    "connection":
                    [
                        {
                            "host": "store-simulator-mq-ibm-mq-qm-eda-integration.assets-arch-eda-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-east.containers.appdomain.cloud",
                            "port": 443
                        }
                    ],
                    "queueManager": "QM1"
                },
                "transmissionSecurity":
                {
                  "cipherSpecification": "ANY_TLS12_OR_HIGHER"
                },
                "type": "clientConnection"
            }
       ]
    }
