apiVersion: v1
kind: ConfigMap
metadata:
  name: store-simulator-cm
data:
  APP_VERSION: 0.0.2
  APP_TARGET_MESSAGING: IBMMQ
  #MQ_HOST: store-simulator-mq-ibm-mq-qm-eda-integration.ingress.domain
  MQ_HOST: ${MQ_ROUTE_HOST}
  #MQ_PORT: "1414" (default)
  MQ_PORT: "443"
  MQ_QMGR: QM1
  MQ_QUEUE_NAME: DEV.QUEUE.1
  MQ_CHANNEL: DEV.APP.SVRCONN
