apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-ccdt-config
data:
  mq-ccdt.json: |-
    {
        "channel":
        [
            {
                "name": "DEV.APP.SVRCONN",
                "clientConnection":
                {
                    "connection":
                    [
                        {
                            "host": "${MQ_ROUTE_HOST}",
                            "port": 443
                        }
                    ],
                    "queueManager": "QM1"
                },
                "transmissionSecurity":
                {
                  "cipherSpecification": "ANY_TLS12_OR_HIGHER"
                },
                "type": "clientConnection"
            }
       ]
    }
