resources:
  - ./config-map.yaml
  - ./route.yaml
  - ./qmgr.yaml


secretGenerator:
  - name: store-simulator-mq-certs
    files:
      - ./certificates/tls.crt
      - ./certificates/tls.key
    type: "kubernetes.io/tls"
  - name: mq-tls-truststore
    files:
      - ./certificates/mq-tls.jks
    literals:
      - password=my-mq-password

generatorOptions:
  disableNameSuffixHash: true
